### ISSUE TITLE
Details about the traj.txt file

### ISSUE THREAD

**Issue by gauraviiita** [concept-graphs/concept-graphs#10]
Hi @krrish94 
I am trying to use the conceptgraph concept on my own dataset. I have data in form of .npz files which contain rgb and d images. Now, I want to know more details about the traj.txt file. Why each row contains 16 entries? Please elaborate about it. In my case robot base is fixed and performing actions on table top environment. 

Thank you

**Comment by georgegu1997** [comment]
Thanks for the interest!

The `traj.txt` file stores the camera poses of the corresponding dataset. Each row corresponds to one RGB/depth image sequentially. The 16 entries in each row are the numbers in the 4x4 camera pose matrix in the row-major order. You should be able to load the poses from `traj.txt` using [this function](https://github.com/concept-graphs/concept-graphs/blob/main/conceptgraph/dataset/datasets_common.py#L467).

**Comment by gauraviiita** [comment]
Hi @georgegu1997 
It is clear now. Thank you for the answer.
