### ISSUE TITLE
No replica_room0.json anywhere for vis_render

### ISSUE THREAD

**Issue by jeezrick** [concept-graphs/concept-graphs#24]
```python    
    # For visualization
    if cfg.vis_render:
        view_param = o3d.io.read_pinhole_camera_parameters(cfg.render_camera_path)
            
        obj_renderer = OnlineObjectRenderer(
            view_param = view_param,
            base_objects = None, 
            gray_map = False,
        )
        frames = []
``` 

In [config](https://github.com/concept-graphs/concept-graphs/blob/5b96cc1b23f5e78120afab7aa602bdac64d65ec9/conceptgraph/configs/slam_pipeline/base.yaml#L72C1-L72C41):
```bash
render_camera_path: "replica_room0.json"
```

running with self.vis_render=True:
```
[Open3D WARNING] Read JSON failed: unable to open file: replica_room0.json
[Open3D WARNING] GLFW Error: X11: The DISPLAY environment variable is missing
[Open3D WARNING] Failed to initialize GLFW
```

I did't see any replica_room0.json anywhere? can you help me?

**Comment by georgegu1997** [comment]
Sorry for missing this file. Please find it here: 
[replica_room0.json](https://github.com/concept-graphs/concept-graphs/files/14498375/replica_room0.json)

If I remember correctly, this should be the camera pose that captures room0 from a top-down view. It's there mostly to conveniently generate some visualization. It is a dumped camera info from the open3d visualizer.

**Comment by georgegu1997** [comment]
Also uploaded it to the codebase in the newest commit.
