### ISSUE TITLE
After streamlined detection version, cannot continue with 3D object mapping process

### ISSUE THREAD

**Issue by eeaurora** [concept-graphs/concept-graphs#27]
Thanks for your amazing work! 

I can run steps “Extract 2D (Detection) Segmentation and per-region features” and “Run the 3D object mapping system” described in README.md. 

I notice you also updated `./scripts/streamlined_detections.py` in “Streamlined Detection Script for ConceptGraphs” to replace `./scripts/generate_gsa_results.py` for faster and simple runs (which I can also run successfully). But after I run this simplified py, I can't continue with “Run the 3D object mapping system” which generate 
```
python slam/cfslam_pipeline_batch.py \
    dataset_root=$REPLICA_ROOT \
    dataset_config=$REPLICA_CONFIG_PATH \
    stride=5 \
    scene_id=$SCENE_NAME \
    spatial_sim_type=overlap \
    mask_conf_threshold=0.25 \
    match_method=sim_sum \
    sim_threshold=${THRESHOLD} \
    dbscan_eps=0.1 \
    gsa_variant=ram_withbg_allclasses \
    skip_bg=False \
    max_bbox_area_ratio=0.5 \
    save_suffix=overlap_maskconf0.25_simsum${THRESHOLD}_dbscan.1
[2024-03-14 20:03:17,696] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Setting image height and width to 680 x 1200
Done! Execution time of get_dataset function: 0.14 seconds
start from create_or_load_colors
cfg.color_file_name gsa_classes_ram_withbg_allclasses
Error executing job with overrides: ['dataset_root=/share/eeaurora/Project/AI/LLM/LLMGraphServer/Datasets/Replica', 'dataset_config=/share/eeaurora/Project/AI/LLM/LLMGraphServer/concept-graphs/conceptgraph/dataset/dataconfigs/replica/replica.yaml', 'stride=5', 'scene_id=room0', 'spatial_sim_type=overlap', 'mask_conf_threshold=0.25', 'match_method=sim_sum', 'sim_threshold=1.2', 'dbscan_eps=0.1', 'gsa_variant=ram_withbg_allclasses', 'skip_bg=False', 'max_bbox_area_ratio=0.5', 'save_suffix=overlap_maskconf0.25_simsum1.2_dbscan.1']
Traceback (most recent call last):
  File "/share/eeaurora/Project/AI/LLM/LLMGraphServer/concept-graphs/conceptgraph/slam/cfslam_pipeline_batch.py", line 142, in main
    classes, class_colors = create_or_load_colors(cfg, cfg.color_file_name)
  File "/share/eeaurora/Project/AI/LLM/LLMGraphServer/concept-graphs/conceptgraph/slam/utils.py", line 43, in create_or_load_colors
    with open(classes_fp, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/share/eeaurora/Project/AI/LLM/LLMGraphServer/Datasets/Replica/room0/gsa_classes_ram_withbg_allclasses.json'
```
It indicates that related json files cannot be loaded.

I notice that the original version of “Extract 2D (Detection) Segmentation and per-region features” can generate json files (include class and color) like  `gsa_classes_none_colors.json`, `gsa_classes_none.json`, `gsa_classes_ram_withbg_allclasses_colors.json` ,`gsa_classes_ram_withbg_allclasses.json`, but the simplified version doesn't generate these json files.

I also notice you add a file called `slam/streamlined_mapping.py`. I try to run it but it get the similar error (I modified the hydra_configs accordingly):

```
python slam/streamlined_mapping.py    
[2024-03-14 20:10:58,821] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Setting image height and width to 680 x 1200
Done! Execution time of get_dataset function: 0.13 seconds
Error executing job with overrides: []
Traceback (most recent call last):
  File "/share/eeaurora/Project/AI/LLM/LLMGraphServer/concept-graphs/conceptgraph/slam/streamlined_mapping.py", line 139, in main
    classes, class_colors = create_or_load_colors(cfg, cfg.color_file_name)
  File "/share/eeaurora/Project/AI/LLM/LLMGraphServer/concept-graphs/conceptgraph/slam/utils.py", line 43, in create_or_load_colors
    with open(classes_fp, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/share/eeaurora/Project/AI/LLM/LLMGraphServer/Datasets/Replica/room0/gsa_classes_ram.json'
```
<img width="346" alt="iShot2024-03-14 20 25 37" src="https://github.com/concept-graphs/concept-graphs/assets/163414162/0fe3c2cd-da40-44b5-9804-8c882a246ccf">

**Question:**
**About the streamlined version**

After I run `./scripts/streamlined_detections.py`,  how to continue with the  `cfslam_pipeline_batch.py` or `streamlined_mapping.py` ?

Thank you.

**Comment by alik-git** [comment]
Thanks for your question @eeaurora!

Yes so right now `cfslam_pipeline_batch.py` is not working with `streamlined_detections.py`, and I am working on the `streamlined_mapping.py` file for that. It's on the [ali-dev](https://github.com/concept-graphs/concept-graphs/tree/ali-dev) branch here:

https://github.com/concept-graphs/concept-graphs/blob/ali-dev/conceptgraph/slam/streamlined_mapping.py

Just know that it's not tested on anything except my machine, and its not stable, I will be pushing lots of new code to it literally later today and over the next few weeks. 

That being said, if you would like to try it and give us your feedback, that would be much appreciated! I am actively working on it, so I am happy to help you with any problems you run into! 

#### Just adding more context:
For streamlined_detections, the classes_file entry in your config should point to the scannet200_classes.txt

It's in the repo here:
https://github.com/concept-graphs/concept-graphs/blob/main/conceptgraph/scannet200_classes.txt

Before we had to make a new classes file on the fly using GroundedDINO or RAM, this is much simpler, the classes stay fixed the whole time. If you want to include some classes that are not there in the scannet200 file, just add them :)

I know all of this should be in the readme, I am just changing stuff everyday so I don't want to keep rewriting it. I will update the readme weekly-ish,

Hope that helps! So happy you're using concept-graphs!
