### ISSUE TITLE
download site for llava-v0-7b

### ISSUE THREAD

**Issue by LeonGoretzkatju** [concept-graphs/concept-graphs#29]
Hello,

Thank you so much for your wonderful work! I was wondering that in your readme file, you said that you used the LLaVA-7B-v0 checkpoint, but now I can only find the delta weight for LLaVA-7B-v0, so could you please share the LLaVA-7B-v0 checkpoint for Scene Graph Generalization? Thank you!

Best regards.

**Comment by krrish94** [comment]
Thanks for your interest @LeonGoretzkatju 

Unfortunately, the LLaVA license does not allow for us to distribute the full weights (you will need to obtain the delta weights, apply them on top of Vicuna).

We will shortly update our codebase to use the latest llava variants (1.5 / 1.6) where you can access the full model weights; and this will no longer continue to be an issue!

**Comment by LeonGoretzkatju** [comment]
> Thanks for your interest @LeonGoretzkatju
> 
> Unfortunately, the LLaVA license does not allow for us to distribute the full weights (you will need to obtain the delta weights, apply them on top of Vicuna).
> 
> We will shortly update our codebase to use the latest llava variants (1.5 / 1.6) where you can access the full model weights; and this will no longer continue to be an issue!

Thank you for your help! Waiting for your update! Thank you so much.

**Comment by georgegu1997** [comment]
I have pushed a quick implementation of using LLaVA 1.6 in the ConceptGraphs codebase, which probably also works fine with LLaVA 1.5. Please check it out in [this branch](https://github.com/concept-graphs/concept-graphs/tree/more-sg). As full weights of LLaVA 1.5/1.6 are published, you should be able to use them without a problem. 

Closing now. Feel free to reopen if you have any further questions.

**Comment by percypeng5221** [comment]
Hi, thanks for the update! The new branch link doesn't seem to exsist, did you merge it into the main branch? Can we just use it the same way as v0 by specifying these variables?
```
export LLAVA_PYTHON_PATH=/path/to/llava
export LLAVA_CKPT_PATH=/path/to/LLaVA-7B-v0
```
