### ISSUE TITLE
Request for the full JSON files that are summarized in the paper.

### ISSUE THREAD

**Issue by 1Konny** [concept-graphs/concept-graphs#30]
Hi! Thanks for your great work!  

Could you release the full JSON files for Listing 1, Listing 2, Listing 3, Listing 4, ..., and so on?

Best,
Wonkwang.

**Comment by georgegu1997** [comment]
Hi, thanks for your interest! 

* Listing 1 is [here](https://github.com/concept-graphs/concept-graphs/blob/main/conceptgraph/scenegraph/GPTPrompt.py#L30)
* Listing 2 is the results generated by the captioning command [here](https://github.com/concept-graphs/concept-graphs/tree/main?tab=readme-ov-file#extract-object-captions-and-build-scene-graphs). 
* Listing 3 and 4 are not in the codebase yet. Please follow issue #39 for updates. 
* Listing 5 and 6 are for the real-robot experiments. Please refer to issue #26 and this [codebase](https://github.com/sachaMorin/concept_graphs_jackal).

**Comment by georgegu1997** [comment]
Closing the issue for now. Feel free to re-open it if needed.
