### ISSUE TITLE
pinhole camera replica room0

### ISSUE THREAD

**Issue by DiTo97** [concept-graphs/concept-graphs#32]
when animating the CFSLAM mapping, a virtual pinhole camera is required.

In the code base, the [JSON for the replica room0 camera](https://github.com/concept-graphs/concept-graphs/blob/main/conceptgraph/replica_room0.json) is provided; would that render other scenes well, as well?

**Comment by georgegu1997** [comment]
The JSON file for room0 was manually adjusted to get camera parameters for the top-down view. It can be obtained on other scenes by pressing ctrl+c when using the visualizer (See [doc](https://www.open3d.org/html/tutorial/Basic/visualization.html#:~:text=To%20retain%20this%20view%20point%2C%20press%20ctrl%2Bc.%20The%20view%20point%20will%20be%20translated%20into%20a%20json%20string%20stored%20in%20clipboard.%20When%20you%20move%20the%20camera%20to%20a%20different%20view%2C%20such%20as%3A) here).

**Comment by krrish94** [comment]
Sorry for the confusion -- I presumed the question was about the config file (camera intrinsics and other metadata for gradslam).

@georgegu1997 is correct. For the visualizer, the camera parameters are obtained experimentally. Generally speaking, the same set of parameters may not work across all scenes, since the scene bounds and camera trajectories differ.

**Comment by DiTo97** [comment]
thank you both, @georgegu1997 and @krrish94.

That's what I suspected, because the rendering looked great for room0, but not so great for the office2 scene or for scenes from our real-world dataset. didn't know about the ctrl+C trick, might be useful to quickly converge to a set of virtual parameters for the rendering camera that fit a scene.

BTW, regardless of the scene, say room0, when running the CFSLAM pipeline batch script with your default configs and incremental online rendering, we keep getting a open3D warning about the viewer and the camera shapes not matching; just a warning, it seemingly works fine, but is it desired behavior?

Also, I might have another question on the animation script rendering the graph on top of the point cloud, but LMK if you want me to open up a new issue.

**Comment by alik-git** [comment]
open a new issue please!

yeah that warning is fine AFAIK, open3d has poor documentation at the moment, so as long as it works... 🤷‍♂️

**Comment by DiTo97** [comment]
> open a new issue please!
> 
> yeah that warning is fine AFAIK, open3d has poor documentation at the moment, so as long as it works... 🤷‍♂️

#34
