### ISSUE TITLE
node attributes in scenegraph animation script

### ISSUE THREAD

**Issue by DiTo97** [concept-graphs/concept-graphs#34]
In the animation script rendering the scenegraph on top of the 3D reconstruction, have you looked into adding metadata as node attributes for visualization purposes? I have tried to do so, but really struggled finding a way with open3D.

since you add nodes as spherical meshes to the scene, I looked for ways to add metadata to a mesh and show them in the canvas, but couldn't really find any of those readily available with a open3D scene, but not sure if you have looked into that.

I am asking because we have extended conceptgraphs with a different multi-modal model, extracting more attributes regarding every detected and segmented object across views (e.g., material, shape, prudence, affordances) and would love to see them in some meaningful manner tied together with the scenegraph rendering as a whole.

LMK if you have any pointers on this that you encountered while developing the animation script.

**Comment by alik-git** [comment]
Hey, sorry about the late response, I've been crazy busy.

Yes so I have also been super frustrated with open3d, and have been integrating [rerun](https://www.rerun.io/) into conceptgraphs for visualizations, where we do indeed have labelling support. See this video (viz stuff starts after 5mins)

https://www.youtube.com/watch?v=ie9VdL7wieY

The code will be pushed a documented soon!! Will ping this thread when it happens. Thank you for using conceptgraphs!! Your project sounds really cool!!

**Comment by alik-git** [comment]
Hey, so I'm still working on the documentation, but try running 

https://github.com/concept-graphs/concept-graphs/blob/ali-dev/conceptgraph/slam/rerun_realtime_mapping.py

?

Lmk if it works, don't forget to install [rerun](https://www.rerun.io/)

**Comment by alik-git** [comment]
Also, would love to learn more about your project. Can you send me a DM on twitter or email? 

twitter: https://twitter.com/alihkw_

email is on my website: https://www.alihkw.com/

**Comment by DiTo97** [comment]
Hi @alik-git,

Thanks for the script, will try that on Monday!

As for our project, I sent you a connection request on LinkedIn, feel free to DM me there. Maybe, we could arrange a chat for next quick. A couple of months ago when we talked with Sacha that was quite useful, so I think having a chat makes the most sense!

**Comment by alik-git** [comment]
Hey so you already know this but the updated code is now documented and I have a tutorial video up as well. 

https://youtu.be/56jEFyrqqpo?si=XaztouZJqNiz7iDW

closing the issue now
