### ISSUE TITLE
supervision: version conflict on ali-dev branch

### ISSUE THREAD

**Issue by NIkolaStaykov** [concept-graphs/concept-graphs#36]
I am using supervision version 0.19.0 in a conda environment and was getting the following error:

> SupervisionWarnings: default is deprecated: `ColorPalette.default()` is deprecated and will be removed in `supervision-0.22.0`. Use `Color.DEFAULT` instead.
Traceback (most recent call last):
  File ".../concept-graphs/conceptgraph/scripts/streamlined_detections.py", line 28, in <module>
    from conceptgraph.utils.vis import vis_result_fast, save_video_detections
  File "...anaconda3/envs/conceptgraph/lib/python3.10/site-packages/conceptgraph/utils/vis.py", line 294, in <module>
    class CustomBoxAnnotator(sv.BoxAnnotator):
TypeError: function() argument 'code' must be code, not str

After changing BoxAnnotator to BoundingBoxAnnotator, as suggested in the 'supervision' code because of a future deprecation, the error was resolved.

**Comment by alik-git** [comment]
Sorry, I'm not sure I understand, you're saying we should use a newer version of supervision, or change the code to work with the version of supervision we are using?

**Comment by georgegu1997** [comment]
@alik-git I think this issue suggests we should replace all `sv.BoxAnnotator` in the code with `sv.BoundingBoxAnnotator`, to accommodate a future change of supervision package. I also saw this deprecation warning in another project recently.

**Comment by alik-git** [comment]
Got it, thank you. Will do.

**Comment by georgegu1997** [comment]
Specifically, I found that changing
```python
    box_annotator = sv.BoxAnnotator(
        color = color,
        text_scale=0.3,
        text_thickness=1,
        text_padding=2,
    )
    mask_annotator = sv.MaskAnnotator(
        color = color,
        opacity=0.35,
    )
```
to 
```python
    box_annotator = sv.BoundingBoxAnnotator(
        color = color,
    )
    label_annontator = sv.LabelAnnotator(
        text_scale=0.3,
        text_thickness=1,
        text_padding=2,
    )
    mask_annotator = sv.MaskAnnotator(
        color = color,
        opacity=0.35,
    )
```
works. 

Closing this for now, as the main branch should work fine with an older version of `supervision` library.
