### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/gaurav/Desktop/Robotics/concept-graphs/Datasets/Replica/room0/gsa_classes_none.json'

### ISSUE THREAD

**Issue by gauraviiita** [concept-graphs/concept-graphs#4]
Hello @krrish94 

I am trying to run the following command, but I am getting an error given below. It is searching for **gsa_classes_none.json'** in the Replica data directory, but I downloaded the dataset using the instructions given. There is no gsa_classes_none.json' file available in the original directory. How can I get this file?

Thanking you

The command I am running:

python conceptgraph/slam/cfslam_pipeline_batch.py \
    dataset_root=/home/gaurav/Desktop/Robotics/concept-graphs/Datasets/Replica \
    dataset_config=/home/gaurav/Desktop/Robotics/concept-graphs/conceptgraph/dataset/dataconfigs/replica/replica.yaml \
    stride=5 \
    scene_id=room0 \
    spatial_sim_type=overlap \
    mask_conf_threshold=0.95 \
    match_method=sim_sum \
    sim_threshold=1.2 \
    dbscan_eps=0.1 \
    gsa_variant=none \
    class_agnostic=True \
    skip_bg=True \
    max_bbox_area_ratio=0.5 \
    save_suffix=overlap_maskconf0.95_simsum1.2_dbscan.1_merge20_masksub \
    merge_interval=20 \
    merge_visual_sim_thresh=0.8 \
    merge_text_sim_thresh=0.8

An error that I am getting:

2023-10-08 22:55:30,508] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Setting image height and width to 680 x 1200
Error executing job with overrides: ['dataset_root=/home/gaurav/Desktop/Robotics/concept-graphs/Datasets/Replica', 'dataset_config=/home/gaurav/Desktop/Robotics/concept-graphs/conceptgraph/dataset/dataconfigs/replica/replica.yaml', 'stride=5', 'scene_id=room0', 'spatial_sim_type=overlap', 'mask_conf_threshold=0.95', 'match_method=sim_sum', 'sim_threshold=1.2', 'dbscan_eps=0.1', 'gsa_variant=none', 'class_agnostic=True', 'skip_bg=True', 'max_bbox_area_ratio=0.5', 'save_suffix=overlap_maskconf0.95_simsum1.2_dbscan.1_merge20_masksub', 'merge_interval=20', 'merge_visual_sim_thresh=0.8', 'merge_text_sim_thresh=0.8']
Traceback (most recent call last):
  File "/home/gaurav/Desktop/Robotics/concept-graphs/conceptgraph/slam/cfslam_pipeline_batch.py", line 138, in main
    classes, class_colors = create_or_load_colors(cfg, cfg.color_file_name)
  File "/home/gaurav/Desktop/Robotics/concept-graphs/conceptgraph/slam/utils.py", line 43, in create_or_load_colors
    with open(classes_fp, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/gaurav/Desktop/Robotics/concept-graphs/Datasets/Replica/room0/gsa_classes_none.json'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by georgegu1997** [comment]
Hi @gauraviiita , thanks for the question! Did you run `scripts/generate_gsa_results.py` before running `slam/cfslam_pipeline_batch.py`?

**Comment by gauraviiita** [comment]
Hi @georgegu1997 

I run the scripts/generate_gsa_results.py but it is showing an error **requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443):** 

Even though I downloaded **pytorch_model.bin** manually and placed it in the current working directory still it is showing an error as I mentioned above. 

Please suggest me way to execute this command **scripts/generate_gsa_results.py**.
Thank you!

**Comment by georgegu1997** [comment]
As mentioned in the other issue, this is probably an Internet connectivity issue of either the Hugging Face or your local side. Can you try running the command using a different machine in a different network, or through a VPN service? 

The No such file or directory error should be gone when you run the `scripts/generate_gsa_results.py` script first. So I am closing this issue. But feel free to discuss what you try and observe.
