### ISSUE TITLE
3D semantic SLAM

### ISSUE THREAD

**Issue by FishofJLlake** [concept-graphs/concept-graphs#40]
Hello, could you confirm if this project supports real-time semantic SLAM mapping for constructing a 3D scene graph? How should I interact with RGBD camera data or the point cloud processed by SLAM? Do you have any suggestions for real-time performance and data transfer interfaces?

**Comment by alik-git** [comment]
Hi there @FishofJLlake,

Sorry about the delay, just got back from travelling. 

ConceptGraphs is a mapping system, not a SLAM system. We take RGB images, depth images, and camera poses as input.

You can search the pointcloud created by ConceptGraphs to find the relevant object given any natural language search query. This is in the README.

Right now, without GPT4V for edges and captioning, the system runs at around 1 fps on a good workstation. We can probably get it a bit better than that, but no promises at the moment. If you'd like to make optimizations yourself, I'd encourage you to submit a PR!

**Comment by krrish94** [comment]
Closing this issue since there aren't immediate plans for full SLAM support.
