### ISSUE TITLE
conceptgraph's code in github about llava's output can't run correctly

### ISSUE THREAD

**Issue by gqsmmz** [concept-graphs/concept-graphs#42]
Hello, I have been reproducing your code for conceptgraph for over a week now, and most of it has been completed. However, unfortunately, there have been some difficult to solve problems in the output of the chat based on the query that I most want to know. 

 I have been experiencing CUDA error: device side assert triggered like following, which is very confusing. 

and i have tried to locate the error for many trials, but still can't know. 

![image](https://github.com/concept-graphs/concept-graphs/assets/87216500/d293291a-d86f-4283-a3b0-e9e4f4b92bea)

**Comment by krrish94** [comment]
@gqsmmz I wonder if the fix here works for you: https://github.com/concept-graphs/concept-graphs/issues/14#issuecomment-1800886598

I have encountered a similar issue befoe when running an incompatible version of the llava codebase. Closing for now, but feel free to reopen if needed.
