### ISSUE TITLE
llava's outputs are same and wrong

### ISSUE THREAD

**Issue by gqsmmz** [concept-graphs/concept-graphs#43]
Hello, your work is very valuable, but when I finally decided to start using your method, I found that the output of the large model only repeated my query and made very inappropriate errors.

![image](https://github.com/concept-graphs/concept-graphs/assets/87216500/c05f2a46-0a64-48f2-8c4a-e79c86ff68ed)

I kept reporting cuda errors while running extract node adaptations for build_scenegraph_cfsslam.py, so I ran all the models and data on the CPU and located the issue of the embedding index being out of bounds. I set the indexes for<0 and>31999 (because the vocabulary is 32000 size) to padding_idx. The program did not report any errors, but I found that the final output of llava was to repeat my query.

![image](https://github.com/concept-graphs/concept-graphs/assets/87216500/4d40a6f4-1b99-4693-9f9e-db72ed3d8813)

I don't know what the problem is, but if you could reply to me, I would greatly appreciate it!

**Comment by georgegu1997** [comment]
Hi, thanks for your question!

I'm not sure whether we met this issue before, but I feel here are a few things that may need your attention:

- Image crops and captions are shown in the `cfslam_captions_llava_debug` folder. Can you give a check on them?
- Can you double-check the input image crops? Are of the expected shape, dtype, and range?
- It may be helpful to make sure the LLaVA model is corrected initialized and loaded. In the main branch, we only tested with `LLaVA-7B-v0`.

**Comment by jarvishou829** [comment]
Solved by following [this](https://github.com/concept-graphs/concept-graphs/issues/22#issuecomment-1905555292)

**Comment by krrish94** [comment]
Closing, similar to https://github.com/concept-graphs/concept-graphs/issues/22
