### ISSUE TITLE
Can realsense  be used to establish concept-graphs ？

### ISSUE THREAD

**Issue by GeLuzhou** [concept-graphs/concept-graphs#44]
Thank you for your excellent work！
I want to use realsense to create a concept-graphs. Have you tried using realsense for real-time mapping？

**Comment by georgegu1997** [comment]
Hi, thanks for your interest. 

We did experiment with a realsense camera in the [ConceptFusion](https://concept-fusion.github.io/) Project and didn't try it in ConceptGraphs. I think realsense camera should work as well. Please refer to #45 for how to write a load for a custom dataset. 

We do not have immediate plans to provide support for realsense cameras on our end.

**Comment by georgegu1997** [comment]
Closing for now. Feel free to re-open if you have any other questions.

**Comment by GeLuzhou** [comment]
> Hi, thanks for your interest.
> 
> We did experiment with a realsense camera in the [ConceptFusion](https://concept-fusion.github.io/) Project and didn't try it in ConceptGraphs. I think realsense camera should work as well. Please refer to #45 for how to write a load for a custom dataset.
> 
> We do not have immediate plans to provide support for realsense cameras on our end.

Thank you very much!
