### ISSUE TITLE
Run on my own dataset

### ISSUE THREAD

**Issue by N-NEJATISHAHIDIN** [concept-graphs/concept-graphs#45]
Hi, can you give me some pointer on how to run it on my own data? 
I have a dataset consisting of RGB, Depth, camera intrinsic and extrinsic.

**Comment by krrish94** [comment]
The easiest way to do this will be to set up a dataset class (e.g., see the example dataset class for the Replica sequences here: https://github.com/concept-graphs/concept-graphs/blob/main/conceptgraph/dataset/datasets_common.py#L426 ).

Once that's done, you should be able to follow instructions from the README to run mapping and captioning for the dataset.

Closing for now, but feel free to reopen if there are further questions
