### ISSUE TITLE
The reconstructed output appears to have ghosting effects.

### ISSUE THREAD

**Issue by libaiwanovo** [concept-graphs/concept-graphs#49]
![r](https://github.com/concept-graphs/concept-graphs/assets/153749298/0ba77b29-83ec-4a5c-8d6a-aea334281af0)
I'm using record3d to work with my own dataset. Even when I move the camera very carefully or move it smoothly, ghosting effects still appear. I don't know what's causing this. Could you help me understand the issue? Thank you.

**Comment by omarrayyann** [comment]
Following. I have the same issue with the real sense camera

**Comment by Eku127** [comment]
> ![r](https://private-user-images.githubusercontent.com/153749298/342607909-0ba77b29-83ec-4a5c-8d6a-aea334281af0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NTMwMjgsIm5iZiI6MTcxOTQ1MjcyOCwicGF0aCI6Ii8xNTM3NDkyOTgvMzQyNjA3OTA5LTBiYTc3YjI5LTgzZWMtNGE1Yy04ZDZhLWFlYTMzNDI4MWFmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QwMTQ1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OTk2YWViZGIzZTU5MDMxMjA4YjZlOTRmNDE0NWY4ZTk5YjY5NDYyMmU2YTg5ZjY5ZTIwMDQxMWFjZGY2N2VhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VQTw87F2xpTvsXVHdtT5GgvNfFWuDImHx6Ndt6zIwJM) I'm using record3d to work with my own dataset. Even when I move the camera very carefully or move it smoothly, ghosting effects still appear. I don't know what's causing this. Could you help me understand the issue? Thank you.

Checkout the intrinsics? If intrinsics are fine, you probably can test with this intrinsics config.

[dataconfig.zip](https://github.com/user-attachments/files/16006672/dataconfig.zip)

**Comment by libaiwanovo** [comment]
> > ![r](https://private-user-images.githubusercontent.com/153749298/342607909-0ba77b29-83ec-4a5c-8d6a-aea334281af0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NTMwMjgsIm5iZiI6MTcxOTQ1MjcyOCwicGF0aCI6Ii8xNTM3NDkyOTgvMzQyNjA3OTA5LTBiYTc3YjI5LTgzZWMtNGE1Yy04ZDZhLWFlYTMzNDI4MWFmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QwMTQ1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OTk2YWViZGIzZTU5MDMxMjA4YjZlOTRmNDE0NWY4ZTk5YjY5NDYyMmU2YTg5ZjY5ZTIwMDQxMWFjZGY2N2VhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VQTw87F2xpTvsXVHdtT5GgvNfFWuDImHx6Ndt6zIwJM) I'm using record3d to work with my own dataset. Even when I move the camera very carefully or move it smoothly, ghosting effects still appear. I don't know what's causing this. Could you help me understand the issue? Thank you.
> 
> Checkout the intrinsics? If intrinsics are fine, you probably can test with this intrinsics config.
> 
> [dataconfig.zip](https://github.com/user-attachments/files/16006672/dataconfig.zip)

Thank you very much! I tried moving even more slowly, and the 2-minute r3d file exceeded 9000 frames. The settings in record3d are as follows:
![record3d-settings](https://github.com/concept-graphs/concept-graphs/assets/153749298/89e9a26b-790b-4836-bd1e-e8422151476b)

The results improved somewhat.

**Comment by krrish94** [comment]
This is an odometry issue -- ConceptGraphs assumes accurate camera poses, so there's not much you can do if the poses are inaccurate. In our experiments, we use ORB-SLAM / RTABMap over Realsense/Kinect RGB-D frames to compute globally consistent camera poses (see https://github.com/sachaMorin/slam-recipes for more details on our configuration).

Closing, since this isn't an issue that can be fixed within the repo.
