### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory.

### ISSUE THREAD

**Issue by gauraviiita** [concept-graphs/concept-graphs#5]
Hi @georgegu1997 
I have corrected my internet, and now scripts/generate_gsa_results.py is working now, and there is no download issues. But now I am getting a CUDA out-of-memory error. I searched on the internet to remove this by reducing the batch size. I tried to search the batch size option, but I am not getting it. Please suggest a possible solution for this problem.

Sorry for bothering you again and again.

The error is as follows.

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacty of 5.80 GiB of which 15.44 MiB is free. Including non-PyTorch memory, this process has 5.78 GiB memory in use. Of the allocated memory 5.14 GiB is allocated by PyTorch, and 139.66 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by krrish94** [comment]
Closing; unrelated to repo
