### ISSUE TITLE
Poor results with r3d

### ISSUE THREAD

**Issue by MicaelCarvalho** [concept-graphs/concept-graphs#54]
Seeing many broken depth features with r3d files — walls and objects slide away and are inconsistent.
@alik-git mentioned this may be a problem with low confidence depth values being used. Opening this issue to track this

**Comment by alik-git** [comment]
if you can share some pictures / screenshots of the issue, and share more about your config setup / hardware etc that would help. thanks!

**Comment by MicaelCarvalho** [comment]
@alik-git here's an example:
- branch: ali-dev
- rerun config modified to have force_detection = True
- r3d file: https://drive.google.com/file/d/1fnk1nMtmyaUbHbqNJuf6ldvAiezzuqB1/view?usp=sharing
- Hardware: RTX 4090, Ryzen Threadripper 5955WX
- Commands:
1. preprocess_r3d_file.py
2. rerun_realtime_mapping.py

Attached screenshot
![concept_graph](https://github.com/user-attachments/assets/813f0b36-cb27-41b7-9eb6-6859fe559b6d)

**Comment by alik-git** [comment]
hmmm I dont think that's a quality of depth issue. I think the depth scale or camera intrinsics or something might be off, resulting in the "repeated wall" pattern you see there.

I would mess around with the depth scale to see if that helps?

**Comment by krrish94** [comment]
Looks like an issue with camera poses or intrinsics. The depth doesn't look bad

**Comment by krrish94** [comment]
I have seen a similar issue before when the camera pose convenion is off. We usually flip the sign for the Y and Z axes of the camera pose (see [here](https://github.com/concept-graphs/concept-graphs/blob/ali-dev/conceptgraph/dataset/datasets_common.py#L848) for the exact code.

**Comment by MicaelCarvalho** [comment]
Thank you @alik-git and @krrish94 — I couldn't find a setting that produces good results. @krrish94 do you recall what changes you made when you had issues? Also tried capturing a new r3d recording in landscape mode instead of portrait, but the preprocess script apparently converts it back to portrait by cropping the sides, and results are still not good.

Have you had good results with r3d files so far? If yes, I suspect it may be something simple / a fix I missed somewhere. Otherwise, perhaps it's not at parity with the other data formats yet? :)

**Comment by krrish94** [comment]
In our experiments with an iPhone 12 Pro, we used the following config

```
camera_params:
  cx: 724.1456298828125
  cy: 950.7185668945312
  fx: 1450.571044921875
  fy: 1450.571044921875
  image_height: 1920
  image_width: 1440
  png_depth_scale: 1000.0
dataset_name: record3d
```

We've had good results with r3d (the depth quality is obv not as nice as an Azure Kinect or a Realsense, but the poses were decent enough to be used across a number of demos)

**Comment by MicaelCarvalho** [comment]
Thanks @krrish94 — couldn't find out what's wrong, besides using an iphone 13 pro instead. Switched temporarily to a different pipeline and will revisit this when I have more time :)

**Comment by krrish94** [comment]
Closing for now, feel free to reopen at a later point
