### ISSUE TITLE
About concept-graph and real robot

### ISSUE THREAD

**Issue by libaiwanovo** [concept-graphs/concept-graphs#56]
Thank you for your excellent work. I am using the ali-dev branch. Could you please advise on how to export PCD point clouds and other files suitable for robots, so that concept-graph and 2D map matching can be achieved for navigation?

**Comment by krrish94** [comment]
We shared code used in the Jackal robot experiments [here](https://github.com/sachaMorin/concept_graphs_jackal)

For map alignment, you can begin by looking at [this launch file](https://github.com/sachaMorin/concept_graphs_jackal/blob/main/launch/align.launch)

Looping @sachaMorin in, to see if he has anything to add

**Comment by sachaMorin** [comment]
Krishna pointed to right file for aligning ConceptGraphs point clouds and robot point clouds. If you need to get a pcd file from the `ali-dev` branch, then @alik-git might know best
