### ISSUE TITLE
About dynamic scene graph 

### ISSUE THREAD

**Issue by MARMOTatZJU** [concept-graphs/concept-graphs#60]
Hello, many thanks for this great work! 

I am considering integrating ConceptGraph and I would like to know if  ConceptGraph supports dynamically updating the scene graph.

Thanks in advance for any clue about it!

**Comment by georgegu1997** [comment]
Hi, thanks for your interest!

ConceptGraphs is not designed for dynamically tracking objects or updating the scene graph online to reflect changes. While we had some prototypes of updating the scene graph in a semi-static environment (updating the scene graph to reflect changes between two scans of the same environment), it is non-trivial to extend it to a fully dynamic setup. 

My preliminary thought is to integrate ConceptGraphs with some great 3D dynamic scene graph pipelines like [this one](https://arxiv.org/abs/2002.06289). We don't have an immediate plan to integrate it on our side.

**Comment by zhirui-gao** [comment]
> Hi, thanks for your interest!
> 
> ConceptGraphs is not designed for dynamically tracking objects or updating the scene graph online to reflect changes. While we had some prototypes of updating the scene graph in a semi-static environment (updating the scene graph to reflect changes between two scans of the same environment), it is non-trivial to extend it to a fully dynamic setup.
> 
> My preliminary thought is to integrate ConceptGraphs with some great 3D dynamic scene graph pipelines like [this one](https://arxiv.org/abs/2002.06289). We don't have an immediate plan to integrate it on our side.

Hi, could you explain how to update the scene graph to reflect changes between two scans of the same environment? Thank you!
