### ISSUE TITLE
Bug at "Consolidate captions" when all detections already computed

### ISSUE THREAD

**Issue by DennisRotondi** [concept-graphs/concept-graphs#65]
Problem:
In rerun_realtime_mapping, when force_detection is set to false and all detections have already been computed, the openai_client will not be initialized, causing the program to crash at the "Consolidate captions" step (line 587, ali-dev branch).

Possible solution:
Initialize the openai_client before line 171, or skip the "Consolidate captions" step if the client has not been initialized.

This issue commonly occurs when running personal experiments, as rerun often crash at "Save recording".

Hope this helps! :)
Dennis

**Comment by georgegu1997** [comment]
Thanks for pointing this out! I've converted this to a PR and will merge it when @alik-git confirms.
