### ISSUE TITLE
IndexError: list index out of range in build_scenegraph function

### ISSUE THREAD

**Issue by XinCheng-lee** [concept-graphs/concept-graphs#66]
https://github.com/concept-graphs/concept-graphs/blob/5c4da70b45f6398d68cb8bfc984502cd9ecaea93/conceptgraph/scenegraph/build_scenegraph_cfslam.py#L783

concept-graphs/conceptgraph/scenegraph/build_scenegraph_cfslam.py", line 804, in build_scenegraph
    if relations[_idx]["object_relation"] != "none of these":
IndexError: list index out of range

**Comment by XinCheng-lee** [comment]
https://github.com/concept-graphs/concept-graphs/blob/5c4da70b45f6398d68cb8bfc984502cd9ecaea93/conceptgraph/scenegraph/build_scenegraph_cfslam.py#L781

**Comment by georgegu1997** [comment]
Hi, thanks for pointing this out. This [commit](https://github.com/concept-graphs/concept-graphs/commit/f33c709a24133c3570547a445e922275b6c3ef68) should be able to fix it.
