### ISSUE TITLE
Can I run the conept-graphs without GPT-4 and LLaVA for a "object-centric concept-fusion"?

### ISSUE THREAD

**Issue by laliwang** [concept-graphs/concept-graphs#7]
Thank you for providing of the source code to your fancy work. I just wonder whether I can build the **CLIP-version concept-graphs** (or say **"object-centric concept-fusion"**) without LLM involving. Sepcifically, It goes like the "Run the 3D object mapping system" in your README may display as object-centric concept-fusion, and I just wonder if it is, thanks!

And BTW, is there a significant gap among your **complete version concept-graphs**, the **object-centric concept-fusion** and the **concept-fusion** in terms of memory, compution and accuracy on descriptive queries? If so, can you make me a brief summary among them quantitively? Thanks a lot for your reply!

**Comment by krrish94** [comment]
If you run all instructions up until [this step](https://github.com/concept-graphs/concept-graphs#visualize-the-object-based-mapping-results), you will the CLIP-variant of concept-graphs.

There is a vast memory usage difference between conceptfusion and the CLIP variant of concept-graphs (this variant of concept graphs only needs the CLIP text encoder to be loaded on GPU; and the per-object CLIP features amount to 100-200 MB GPU/CPU memory per scene -- on the other hand, GPU usage for conceptfusion routinely is between 16G-32G or more).

**Comment by krrish94** [comment]
Table III of our paper measures the difference between CLIP and LLM variants of ConceptGraphs. As you can see from Table II, ConceptFusion and the CLIP variant of ConceptGraphs have similar performance on 3D segmentation (the key difference is the lower memory footprint of ConceptGraphs) -- and in table III, we see there's a difference (particularly on complex queries, or queries involving negation) between the CLIP and LLM variants of ConceptGraphs.
