### ISSUE TITLE
Error while running rerun_realtime_mapping.py

### ISSUE THREAD

**Issue by sunwookim1214** [concept-graphs/concept-graphs#70]
I get the following error when running the script:

Traceback (most recent call last):
  File "/home/rirolab/concept-graphs/conceptgraph/slam/rerun_realtime_mapping.py", line 65, in <module>
    from conceptgraph.utils.vis import (
  File "/home/rirolab/concept-graphs/conceptgraph/utils/vis.py", line 205, in <module>
    color: Color | ColorPalette = ColorPalette.default(),
AttributeError: type object 'ColorPalette' has no attribute 'default'

I think this is a version issue. If anyone knows how I can fix this problem, I'd be very grateful.

**Comment by sunwookim1214** [comment]
Fixed by downgrading supervision package to 0.21.0.

**Comment by ricber** [comment]
I also had to downgrade numpy to 1.24.3

**Comment by stone-ziyan** [comment]
use "ColorPalette.DEFAULT" instead
